netutils/webclient: fix 'defined but not used'
Fixed an error that can be found when using the latest toolchain.

webclient.c:190:19: error: 'g_httpuseragentfields' defined but not used
[-Werror=unused-const-variable=]
 static const char g_httpuseragentfields[] = "Connection: close\r\n"
                   ^~~~~~~~~~~~~~~~~~~~~

Change-Id: I235aa69ead12f7834f8b3dfb2df122b9152ac589
Signed-off-by: Junhwan Park <junhwan.park@samsung.com>