driver/mtd: fix 'defined but not used'
Fixed an error that can be found when using the latest toolchain.

driver/mtd/smart.c:209:22: error: 'gWearBitToLevelMap4' defined but not
used [-Werror=unused-const-variable=]
 static const uint8_t gWearBitToLevelMap4[] = {
                      ^~~~~~~~~~~~~~~~~~~
driver/mtd/smart.c:198:22: error: 'gWearLevelToBitMap4' defined but not
used [-Werror=unused-const-variable=]
 static const uint8_t gWearLevelToBitMap4[] = {
                      ^~~~~~~~~~~~~~~~~~~

Change-Id: Id3889f748992aec54482e4ac3e44894571fff9e7
Signed-off-by: Junhwan Park <junhwan.park@samsung.com>