libc/stdio: fix 'defined but not used'
Fixed an error that can be found when using the latest toolchain.

stdio/lib_dtoa.c:738:21: error: 'tinytens' defined but not used
[-Werror=unused-const-variable=]
 static const double tinytens[] = { 1e-16, 1e-32, 1e-64, 1e-128, 1e-256
	 };
                     ^~~~~~~~

Change-Id: Ic8ad0b6dace8f2e49058d68d4cbf015faa60e91c
Signed-off-by: Junhwan Park <junhwan.park@samsung.com>